//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDetail
    {
        public string uerName { get; set; }
        public string passTxt { get; set; }
    }
}
