//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllDetail
    {
        [Key]
        [Required]
        public int associate_id { get; set; }
        [Required]
        public string associate_name { get; set; }
        [Required]
        public string associate_training_id { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> doj_associate { get; set; }
        [Required]
        public string associate_loc { get; set; }
        [Required]
        public string training_module_id { get; set; }
        [Required]
        public string business_unit_name { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> startdate { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> enddate { get; set; }
    }
}
