//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateDetail
    {
        public int associate_id { get; set; }
        public string associate_name { get; set; }
        public string training_module_id { get; set; }
        public Nullable<System.DateTime> doj { get; set; }
        public string loc { get; set; }
        public string phno { get; set; }
        public string email { get; set; }
    }
}
