//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchDetail
    {
        [Key]
        [Required]
        public string training_module_id { get; set; }
        [Required]
        public Nullable<int> business_unit_id { get; set; }
        [Required]
        public Nullable<System.DateTime> startdate { get; set; }
        [Required]
        public Nullable<System.DateTime> enddate { get; set; }
    }
}
