//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingModule()
        {
            this.BatchDetails = new HashSet<BatchDetail>();
        }
        [Key]
        [Required(ErrorMessage ="This field can must be full")]
        public int business_unit_id { get; set; }
        [Required(ErrorMessage = "This field can must be full")]

        public string business_unit_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchDetail> BatchDetails { get; set; }
    }
}
