//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerDetail
    {
        [Key]
        [Required(ErrorMessage = "This field can must be full")]
        public int trainer_id { get; set; }
        [Required(ErrorMessage = "This field can must be full")]
        public string trainer_name { get; set; }
        [Required(ErrorMessage = "This field can must be full")]
        public string training_module_id { get; set; }
        [Required(ErrorMessage = "This field can must be full")]
        public string business_unit_name { get; set; }
        [Required(ErrorMessage = "This field can must be full")]
        public string phno { get; set; }
        [Required(ErrorMessage = "This field can must be full")]
        public string email { get; set; }
    
        public virtual BatchDetail BatchDetail { get; set; }
    }
}
