//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerDetail
    {
        public int trainer_id { get; set; }
        public string trainer_name { get; set; }
        public string training_module_id { get; set; }
        public string business_unit_name { get; set; }
        public string phno { get; set; }
        public string email { get; set; }
    }
}
